/*
 * Validates that golden tables generated by the delta-semantics-tester
 * are readable by Delta Kernel Java. These tables were oracle-verified
 * and exported in the standard golden table format.
 */
package io.delta.kernel.defaults

import io.delta.golden.GoldenTableUtils.goldenTablePath
import io.delta.kernel.defaults.utils.TestUtils

import org.scalatest.funsuite.AnyFunSuite

class SemanticsTesterGoldenTableSuite extends AnyFunSuite with TestUtils {

  private val semanticsTesterTables = Seq(
    "semantics-tester-real_append_read_agreement",
    "semantics-tester-real_multi_append_read",
    "semantics-tester-real_partition_filter",
    "semantics-tester-real_delete_and_read",
    "semantics-tester-real_optimize_invariance",
    "semantics-tester-real_time_travel_versions")

  for (tableName <- semanticsTesterTables) {
    test(s"semantics-tester: read $tableName") {
      val tablePath = goldenTablePath(tableName)
      val snapshot = latestSnapshot(tablePath)
      val version = snapshot.getVersion()
      assert(version >= 0, s"Expected valid version for $tableName, got $version")

      // Verify we can read the schema
      val schema = snapshot.getSchema()
      assert(schema.length() > 0, s"Expected non-empty schema for $tableName")

      // Verify we can scan and read rows
      val rows = readSnapshot(snapshot)
      assert(rows.nonEmpty, s"Expected at least one row in $tableName")
    }
  }
}
